spring:
  cassandra:
    keyspace-name: employee_db
    contact-points: ${SCYLLA_HOST:localhost}
    port: ${SCYLLA_PORT:9042}
    username: ${SCYLLA_USER:scylladb}
    password: ${SCYLLA_PASSWORD:password}
    local-datacenter: datacenter1
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  health:
    cassandra:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    path: /salary-documentation
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /salary-api-docs
  show-actuator: true
